#include "Sampler.hpp"

std::string Resources::defaultSamplersNames[Sampler::DefaultSamplers::COUNT] = {
	"DEFAULT_SAMPLER_NEAREST_CLAMP",
	"DEFAULT_SAMPLER_NEAREST_REPEAT",
	"DEFAULT_SAMPLER_LINEAR_REPEAT",
	"DEFAULT_SAMPLER_LINEAR_CLAMP",
	"DEFAULT_SAMPLER_LINEAR_MIPMAP_LINEAR_CLAMP"
};